name: 'Slack PR Action'
description: 'Actions that will work with Slack'
inputs:
  slack_hook:
    description: 'Who to greet'
    required: true
    default: 'World'
  slack_json:
    description: 'Slack JSON'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'activity'
  color: 'purple'
