name: 'Slack PR Action'
description: 'Actions that will work with Slack'
inputs:
  slack_hook:
    description: 'Who to greet'
    required: true
    default: 'World'
  gh_token:
    description: 'Github Token'
    required: true
    default: ''
  event_num:
    description: 'Event Number'
    required: true
    default: ''
  repo:
    description: 'Repo Info'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'purple'
